# Generated by Django 4.2.11 on 2024-05-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gyms/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
        ),
        migrations.RenameField(
            model_name='poster',
            old_name='image',
            new_name='picture',
        ),
        migrations.AddField(
            model_name='poster',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер группы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trainees',
            field=models.ManyToManyField(blank=True, related_name='trainers', to='main.userprofile'),
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание зала')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.location')),
                ('pictures', models.ManyToManyField(related_name='gyms', to='main.image')),
                ('users', models.ManyToManyField(related_name='user_profiles', to='main.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gyms',
            field=models.ManyToManyField(related_name='members', to='main.gym'),
        ),
    ]
